apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    fleet.gke.io/rrb-resource-link: //gkehub.googleapis.com/projects/877381117738/locations/global/namespaces/ns1/rbacrolebindings/rbac-1
  labels:
    fleet.gke.io/actuation-active: "true"
  name: fleet-rrb-actuation-rbac-1
  namespace: ns1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: nanyu@google.com
